"""Initial migration

Revision ID: 26bfbfdfea05
Revises: a7ce69654a33
Create Date: 2025-02-12 15:01:20.041287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bfbfdfea05'
down_revision: Union[str, None] = 'a7ce69654a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_feedback_reason'), 'feedback', ['reason'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_reason'), table_name='feedback')
    op.drop_column('feedback', 'reason')
    # ### end Alembic commands ###
