"""Final migration

Revision ID: cca976f3b132
Revises: 26bfbfdfea05
Create Date: 2025-02-12 15:02:18.664639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca976f3b132'
down_revision: Union[str, None] = '26bfbfdfea05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_reason', table_name='feedback')
    op.drop_column('feedback', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_feedback_reason', 'feedback', ['reason'], unique=False)
    # ### end Alembic commands ###
